language: node_js

node_js:
  - '0.10'

sudo: false

git:
  depth: 1

before_script:
  - chmod +x .travis/after_success.sh
  - chmod +x ./deploy

branches:
  except:
    - gh-pages

env:
  global:
    - REPO="git@github.com:jessy1092/explore-africa"
    - secure: e+2mcfXJ/1tLdU1Jgtxyz84ty72m6jv6mdKrjKBk+3fduqJb3CIor8ZUkIqG22H4KVUbIGZiSdBlQpmGB+D+FBfEx8FkPnbihZAFlGrjUALEriZ+wlqwF+5TBwS9ebyU6OPq+haJdo+EFjJuZkEi/waLp2V4um+uAtb/NQcYZSg=

after_success: ".travis/after_success.sh"
