language: node_js

node_js:
  - '4'

sudo: false

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

git:
  depth: 1

before_script:
  - chmod +x .travis/after_success.sh
  - chmod +x ./deploy

script:
  - npm test

after_script:
  - cat coverage/phantomjs/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  except:
    - gh-pages

env:
  global:
    - REPO="git@github.com:wowafrica/wowafrica"
    - secure: f+Ru9XNRGCePbX9dz5W1Fkutgqo+vOESp5AOLH9d4R/9D8x3aIzExg8OOmxDKDlrbvl8GKiwzaTG7STgxBhEp2NwWyT6Bd77xGI848ChUtNuqezWv0jMwX/Sm/zJNzWfF/PIK5MYO45LGfifJK17W2pG3KE05YbzXyajslF8D7A=

after_success: .travis/after_success.sh

notifications:
  slack:
    secure: O0GRmyRZHfwFEyr+wCHqt9hT3ul2Y3/Ne3qPgbXSryaZlzuebe62Cqk2D69TMt3mRgAVRJL9Hoe9u+4OZa57MDwc+BqnH7osvnlU8SPuTO/7vzjgCyUfXGhvvvkRH+tYC9j9w1xTgxuNOLjXUFskCzaiwNV6TszoAq2VGj1WC+Q=
